# Generated by Django 4.2.7 on 2023-12-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210730_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifyblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
